export const VOCABULARY = [
  { id: 1, name: "Monte", description: "Terreno cubierto de árboles.", example: "El monte estaba lleno de vida después de la lluvia." },
  { id: 2, name: "Caja", description: "Recipiente cuadrado con tapa.", example: "Guardó sus recuerdos en una caja de madera." },
  { id: 3, name: "Misterioso", description: "Que causa curiosidad o asombro.", example: "Un sonido misterioso se escuchó desde el bosque." },
  { id: 4, name: "Gruñido", description: "Sonido fuerte y bajo, de enojo o amenaza.", example: "El perro emitió un gruñido al ver al extraño." },
  { id: 5, name: "Difunto", description: "Persona que ha muerto.", example: "El retrato del difunto colgaba sobre la chimenea." },
  { id: 6, name: "Valiente", description: "Que no tiene miedo.", example: "El valiente caballero se enfrentó al dragón sin dudar." },
  { id: 7, name: "Advertencia", description: "Aviso para prevenir un peligro.", example: "Ignoró la advertencia del guardia y cruzó el puente." },
  { id: 8, name: "Río", description: "Corriente de agua natural.", example: "El río serpentea a través del valle." },
  { id: 9, name: "Leyenda", description: "Relato tradicional transmitido por generaciones.", example: "La leyenda cuenta que un tesoro está escondido en esas montañas." },
  { id: 10, name: "Guardián", description: "El que cuida o protege algo.", example: "El guardián del templo no dejaba pasar a nadie." },
  { id: 11, name: "Niebla", description: "Nube baja que dificulta la visión.", example: "La niebla cubría todo el camino, haciendo difícil avanzar." },
  { id: 12, name: "Lamento", description: "Expresión de tristeza o dolor.", example: "Se escuchó un lamento entre los árboles." },
  { id: 13, name: "Sombra", description: "Oscuridad producida por un cuerpo que impide el paso de la luz.", example: "Una sombra se movió detrás de la puerta." },
  { id: 14, name: "Ecos", description: "Repetición de un sonido reflejado.", example: "Los ecos de sus pasos resonaban en la cueva." },
  { id: 15, name: "Tormenta", description: "Fenómeno con fuertes vientos y lluvia.", example: "La tormenta comenzó justo cuando salimos de casa." },
  { id: 16, name: "Silencio", description: "Ausencia de ruido.", example: "El silencio en el bosque era inquietante." },
  { id: 17, name: "Espíritu", description: "Ser inmaterial o alma.", example: "Dicen que el espíritu del viejo marinero aún ronda por allí." },
  { id: 18, name: "Antiguo", description: "Muy viejo o de tiempos pasados.", example: "Encontraron un libro antiguo cubierto de polvo." },
  { id: 19, name: "Oscuro", description: "Que tiene poca luz.", example: "El pasillo oscuro conducía a una habitación secreta." },
  { id: 20, name: "Hechizo", description: "Palabras o actos mágicos.", example: "El mago lanzó un hechizo para proteger el castillo." },
  { id: 21, name: "Furioso", description: "Muy enojado.", example: "El león estaba furioso tras perder a su presa." },
  { id: 22, name: "Desesperado", description: "Sin esperanza.", example: "Se sintió desesperado al no encontrar salida del laberinto." },
  { id: 23, name: "Engañar", description: "Hacer creer algo falso.", example: "No debes engañar a tus amigos con mentiras." },
  { id: 24, name: "Sombrío", description: "Con poca luz o triste.", example: "El bosque sombrío parecía esconder secretos." },
  { id: 25, name: "Amargura", description: "Tristeza profunda.", example: "Sentía amargura al recordar su infancia difícil." },
  { id: 26, name: "Rencor", description: "Enojo guardado por mucho tiempo.", example: "El rencor lo consumía cada vez que pensaba en la traición." },
  { id: 27, name: "Rastro", description: "Señal que deja algo al pasar.", example: "El lobo dejó un rastro en la nieve que seguimos." },
  { id: 28, name: "Lamento", description: "Expresión de dolor o tristeza.", example: "Un lamento se oyó desde la casa abandonada." },
  { id: 29, name: "Misterio", description: "Cosa difícil de entender.", example: "El misterio del castillo atrajo a muchos curiosos." },
  { id: 30, name: "Aventura", description: "Suceso emocionante o peligroso.", example: "Partieron en una aventura por la selva desconocida." },
  { id: 31, name: "Niebla", description: "Nube baja que dificulta ver.", example: "La niebla cubría todo el valle al amanecer." },
  { id: 32, name: "Tormenta", description: "Fenómeno con lluvia y truenos.", example: "La tormenta destruyó varios árboles del parque." },
  { id: 33, name: "Espanto", description: "Miedo muy grande.", example: "Sintió espanto al ver la sombra moverse sola." },
  { id: 34, name: "Difícil", description: "Que cuesta hacer o entender.", example: "Resolver el acertijo fue difícil pero divertido." },
  { id: 35, name: "Somnoliento", description: "Con sueño o cansancio.", example: "El gato parecía somnoliento bajo el sol." },
  { id: 36, name: "Cruzar", description: "Pasar de un lado a otro.", example: "Tuvimos que cruzar el río con cuidado." },
  { id: 37, name: "Desgracia", description: "Hecho triste o malo.", example: "La pérdida del barco fue una gran desgracia." },
  { id: 38, name: "Encantado", description: "Bajo un hechizo o embrujo.", example: "El bosque estaba encantado y lleno de magia." },
  { id: 39, name: "Atónito", description: "Sorprendido o asombrado.", example: "Quedó atónito al ver la aurora boreal." },
  { id: 40, name: "Retumbar", description: "Sonar con fuerza y eco.", example: "Los tambores retumbaban en toda la ciudad." },
  { id: 41, name: "Callejón", description: "Calle angosta.", example: "El callejón llevaba a una plaza escondida." },
  { id: 42, name: "Adoquinado", description: "Cubierto con piedras.", example: "El camino adoquinado crujía bajo nuestros pies." },
  { id: 43, name: "Crujido", description: "Ruido al romperse algo.", example: "Un crujido se oyó al abrir la vieja puerta." },
  { id: 44, name: "Macabro", description: "Relacionado con la muerte.", example: "El castillo tenía un aire macabro y misterioso." },
  { id: 45, name: "Infiel", description: "Que no cumple su compromiso.", example: "El amigo infiel traicionó su confianza." },
  { id: 46, name: "Ebrio", description: "Que ha bebido mucho alcohol.", example: "El hombre ebrio no podía caminar recto." },
  { id: 47, name: "Enloquecer", description: "Perder la razón.", example: "El calor del desierto podría hacerlo enloquecer." },
  { id: 48, name: "Silbido", description: "Sonido hecho con los labios.", example: "Se escuchó un silbido que hizo eco en la cueva." },
  { id: 49, name: "Sombra", description: "Figura oscura que forma la luz al bloquearse.", example: "Su sombra se proyectaba sobre la pared." },
  { id: 50, name: "Torcido", description: "Que no está derecho.", example: "El árbol estaba torcido por el viento." },
  { id: 51, name: "Chispa", description: "Partícula encendida que salta de un fuego.", example: "Una chispa saltó de la hoguera y encendió la leña seca." },
  { id: 52, name: "Lumbre", description: "Fuego o luz.", example: "Encendieron la lumbre para calentarse." },
  { id: 53, name: "Oscuridad", description: "Falta de luz.", example: "La oscuridad hacía difícil ver el camino." },
  { id: 54, name: "Temor", description: "Sentimiento de miedo.", example: "Sentía temor antes de entrar a la cueva." },
  { id: 55, name: "Arrastrar", description: "Mover algo por el suelo.", example: "Tuvieron que arrastrar la roca hasta la orilla." },
  { id: 56, name: "Grito", description: "Voz fuerte de miedo o dolor.", example: "Un grito rompió el silencio de la noche." },
  { id: 57, name: "Cautivo", description: "Prisionero.", example: "El cautivo esperaba ser liberado." },
  { id: 58, name: "Suplicar", description: "Pedir con mucha insistencia.", example: "Suplicó que lo perdonaran por su error." },
  { id: 59, name: "Rogar", description: "Pedir algo con humildad.", example: "Rogó por la salud de su familia." },
  { id: 60, name: "Peligro", description: "Situación que puede causar daño.", example: "Se acercaban a un lugar de peligro." },
  { id: 61, name: "Trampa", description: "Engaño preparado para atrapar.", example: "El cazador preparó una trampa para el zorro." },
  { id: 62, name: "Lamento", description: "Expresión de dolor.", example: "Sus lamentos se escuchaban desde la montaña." },
  { id: 63, name: "Despedir", description: "Decir adiós o alejar a alguien.", example: "Despidió a su amigo con un abrazo." },
  { id: 64, name: "Alma", description: "Parte espiritual de una persona.", example: "Se dice que su alma es pura y bondadosa." },
  { id: 65, name: "Hechicero", description: "Persona que hace magia.", example: "El hechicero lanzó un conjuro sobre el castillo." },
  { id: 66, name: "Encantamiento", description: "Conjuro mágico.", example: "El encantamiento protegía la puerta secreta." },
  { id: 67, name: "Espíritu", description: "Ser invisible que representa el alma.", example: "El espíritu de la montaña se mostraba al amanecer." },
  { id: 68, name: "Criatura", description: "Ser vivo o imaginario.", example: "La criatura del lago sorprendió a los pescadores." },
  { id: 69, name: "Difunto", description: "Muerto o fallecido.", example: "El difunto fue recordado con flores y velas." },
  { id: 70, name: "Aparición", description: "Algo o alguien que se muestra de repente.", example: "La aparición asustó a todos en la casa vieja." },
  { id: 71, name: "Humo", description: "Gas que sale de algo que se quema.", example: "El humo de la chimenea se elevaba hacia el cielo." },
  { id: 72, name: "Somnolencia", description: "Deseo de dormir.", example: "La somnolencia lo venció durante la larga caminata." },
  { id: 73, name: "Vapor", description: "Gas que se eleva al calentar agua.", example: "El vapor de la olla llenaba la cocina." },
  { id: 74, name: "Calma", description: "Tranquilidad.", example: "Después de la tormenta, reinó la calma en el valle." },
  { id: 75, name: "Desvelo", description: "Falta de sueño.", example: "El desvelo lo dejó agotado al día siguiente." },
  { id: 76, name: "Castigo", description: "Pena por un error.", example: "El castigo fue justo por romper la regla." },
  { id: 77, name: "Perdón", description: "Acción de disculpar a alguien.", example: "Pidió perdón por su comportamiento." },
  { id: 78, name: "Promesa", description: "Compromiso de hacer algo.", example: "Cumplió la promesa de ayudar a su vecino." },
  { id: 79, name: "Mentira", description: "Cosa que no es verdad.", example: "No le creas, eso es una mentira." },
  { id: 80, name: "Verdad", description: "Lo que es real o cierto.", example: "Finalmente dijo la verdad sobre lo sucedido." },
  { id: 81, name: "Rencoroso", description: "Que no olvida una ofensa.", example: "Es rencoroso y nunca perdona a sus enemigos." },
  { id: 82, name: "Pacífico", description: "Tranquilo y sin violencia.", example: "El lago parecía pacífico al amanecer." },
  { id: 83, name: "Fiel", description: "Que cumple con su palabra.", example: "Es un amigo fiel que siempre te apoya." },
  { id: 84, name: "Malvado", description: "Que hace el mal.", example: "El villano malvado planeaba apoderarse del reino." },
  { id: 85, name: "Bondad", description: "Inclinación a hacer el bien.", example: "Su bondad se notaba en cada gesto." },
  { id: 86, name: "Justicia", description: "Dar a cada uno lo que merece.", example: "La justicia prevaleció al final del juicio." },
  { id: 87, name: "Injusticia", description: "Lo contrario de justicia.", example: "Lucharon contra la injusticia del sistema." },
  { id: 88, name: "Crueldad", description: "Gusto en causar dolor.", example: "La crueldad del enemigo era aterradora." },
  { id: 89, name: "Súplica", description: "Ruego con sentimiento.", example: "Hizo una súplica para que lo dejaran entrar." },
  { id: 90, name: "Luz", description: "Energía que permite ver.", example: "La luz de la luna iluminaba el bosque." },
  { id: 91, name: "Tiniebla", description: "Oscuridad total.", example: "La tiniebla cubría la cueva por completo." },
  { id: 92, name: "Fuego", description: "Calor y luz producidos por la combustión.", example: "El fuego del hogar daba calor a la familia." },
  { id: 93, name: "Ceniza", description: "Polvo gris que queda del fuego.", example: "La chimenea estaba llena de ceniza." },
  { id: 94, name: "Sombrero", description: "Prenda que cubre la cabeza.", example: "Llevaba un sombrero para protegerse del sol." },
  { id: 95, name: "Trenza", description: "Cabello entrelazado.", example: "Ella lucía una trenza larga y brillante." },
  { id: 96, name: "Cabellera", description: "Conjunto de cabellos.", example: "Su cabellera rubia caía sobre los hombros." },
  { id: 97, name: "Aroma", description: "Olor agradable.", example: "El aroma del pan recién horneado llenaba la cocina." },
  { id: 98, name: "Perfume", description: "Sustancia con buen olor.", example: "El perfume de flores era muy intenso." },
  { id: 99, name: "Joya", description: "Adorno valioso.", example: "La corona estaba llena de joyas brillantes." },
  { id: 100, name: "Tesoro", description: "Conjunto de riquezas guardadas.", example: "Encontraron un tesoro escondido en la isla." },
  { id: 101, name: "Cofre", description: "Caja donde se guardan cosas de valor.", example: "El cofre contenía monedas antiguas." },
  { id: 102, name: "Llave", description: "Instrumento para abrir cerraduras.", example: "La llave estaba escondida bajo la maceta." },
  { id: 103, name: "Puerta", description: "Abertura para entrar o salir.", example: "La puerta de la cabaña estaba abierta." },
  { id: 104, name: "Ventana", description: "Abertura que deja pasar luz o aire.", example: "La ventana daba vista al jardín." },
  { id: 105, name: "Reloj", description: "Aparato que indica la hora.", example: "El reloj marcaba las doce en punto." },
  { id: 106, name: "Somnoliento", description: "Con sueño.", example: "El niño estaba somnoliento después del almuerzo." },
  { id: 107, name: "Despierto", description: "Sin sueño, atento.", example: "Permaneció despierto toda la noche estudiando." },
  { id: 108, name: "Veloz", description: "Rápido.", example: "El guepardo es un animal veloz." },
  { id: 109, name: "Lento", description: "Que se mueve despacio.", example: "El caracol era lento pero constante." },
  { id: 110, name: "Correr", description: "Moverse rápidamente.", example: "Le gusta correr todas las mañanas en el parque." },
  { id: 111, name: "Caer", description: "Perder el equilibrio y bajar al suelo.", example: "Casi se cae por la escalera resbaladiza." },
  { id: 112, name: "Levantar", description: "Poner algo en posición vertical.", example: "Ayudó a levantar la caja pesada." },
  { id: 113, name: "Saltar", description: "Elevarse del suelo con impulso.", example: "El niño saltó sobre los charcos." },
  { id: 114, name: "Volar", description: "Moverse por el aire.", example: "El pájaro podía volar muy alto." },
  { id: 115, name: "Caminar", description: "Desplazarse a pie.", example: "Le gusta caminar por el bosque." },
  { id: 116, name: "Andar", description: "Sinónimo de caminar.", example: "Andaba por la ciudad admirando los edificios." },
  { id: 117, name: "Seguir", description: "Ir detrás de alguien o algo.", example: "Decidió seguir al grupo por el sendero." },
  { id: 118, name: "Perseguir", description: "Buscar con intención de alcanzar.", example: "El perro empezó a perseguir al gato." },
  { id: 119, name: "Escapar", description: "Huir de un peligro.", example: "Logró escapar del incendio a tiempo." },
  { id: 120, name: "Correría", description: "Acción de correr o moverse rápido.", example: "La correcorría por el campo emocionaba a los niños." },
  { id: 121, name: "Temblor", description: "Movimiento del suelo.", example: "El temblor hizo que los objetos cayeran de las mesas." },
  { id: 122, name: "Sismo", description: "Sacudida de la tierra.", example: "El sismo se sintió durante varios segundos." },
  { id: 123, name: "Explosión", description: "Estallido fuerte.", example: "La explosión iluminó toda la ciudad por un instante." },
  { id: 124, name: "Trueno", description: "Sonido después de un relámpago.", example: "El trueno retumbó en las montañas." },
  { id: 125, name: "Relámpago", description: "Luz fuerte que se ve en tormentas.", example: "Un relámpago iluminó el cielo nocturno." },
  { id: 126, name: "Lluvia", description: "Gotas de agua que caen del cielo.", example: "La lluvia refrescó el jardín." },
  { id: 127, name: "Granizo", description: "Bolas de hielo que caen del cielo.", example: "El granizo rompió varias ventanas." },
  { id: 128, name: "Nube", description: "Vapor de agua en el cielo.", example: "Una nube oscura cubría el sol." },
  { id: 129, name: "Cielo", description: "Espacio donde están el sol y las estrellas.", example: "El cielo estaba despejado y azul." },
  { id: 130, name: "Estrella", description: "Cuerpo luminoso en el espacio.", example: "La estrella más brillante se veía desde la montaña." },
  { id: 131, name: "Luna", description: "Satélite natural de la Tierra.", example: "La luna llena iluminaba el bosque." },
  { id: 132, name: "Sol", description: "Estrella que da luz y calor.", example: "El sol calienta la tierra durante el día." },
  { id: 133, name: "Amanecer", description: "Momento en que sale el sol.", example: "Disfrutamos del amanecer en la playa." },
  { id: 134, name: "Atardecer", description: "Momento en que el sol se oculta.", example: "El atardecer pintaba el cielo de naranja y rosa." },
  { id: 135, name: "Noche", description: "Tiempo sin sol.", example: "La noche estaba tranquila y silenciosa." },
  { id: 136, name: "Día", description: "Tiempo con luz solar.", example: "Pasamos el día explorando el bosque." },
  { id: 137, name: "Sombrío", description: "Con poca luz.", example: "El callejón sombrío parecía peligroso." },
  { id: 138, name: "Brillante", description: "Que brilla mucho.", example: "Las joyas eran tan brillantes que cegaban la vista." },
  { id: 139, name: "Resplandor", description: "Luz intensa.", example: "El resplandor del fuego iluminaba la cueva." },
  { id: 140, name: "Reflejo", description: "Imagen que rebota en una superficie.", example: "Se vio su reflejo en el lago." },
  { id: 141, name: "Rostro", description: "Cara de una persona.", example: "Su rostro mostraba felicidad." },
  { id: 142, name: "Mirada", description: "Dirección en que se fijan los ojos.", example: "Su mirada estaba llena de asombro." },
  { id: 143, name: "Ojos", description: "Órganos que permiten ver.", example: "Sus ojos brillaban con emoción." },
  { id: 144, name: "Boca", description: "Abertura por donde se come o habla.", example: "La boca del lobo se abrió mostrando sus dientes." },
  { id: 145, name: "Risa", description: "Sonido que se hace al reír.", example: "Su risa llenaba la habitación de alegría." },
  { id: 146, name: "Llanto", description: "Acción de llorar.", example: "El llanto del bebé despertó a todos." },
  { id: 147, name: "Suspiro", description: "Aire que se exhala con emoción.", example: "Dejó escapar un suspiro de alivio." },
  { id: 148, name: "Silencio", description: "Ausencia de ruido.", example: "El silencio en la biblioteca era absoluto." },
  { id: 149, name: "Ruido", description: "Sonido fuerte.", example: "El ruido de la construcción molestaba a los vecinos." },
  { id: 150, name: "Voz", description: "Sonido que sale al hablar.", example: "Su voz era suave y melodiosa." },
  { id: 151, name: "Palabra", description: "Conjunto de sonidos con significado.", example: "Cada palabra debía ser cuidadosamente elegida." },
  { id: 152, name: "Frase", description: "Conjunto de palabras con sentido completo.", example: "La frase inspiró a todos los presentes." },
  { id: 153, name: "Cuento", description: "Narración breve.", example: "Le contaron un cuento antes de dormir." },
  { id: 154, name: "Relato", description: "Historia contada.", example: "El relato del viaje cautivó a los niños." },
  { id: 155, name: "Leyenda", description: "Narración tradicional con elementos mágicos.", example: "La leyenda hablaba de un dragón escondido." },
  { id: 156, name: "Historia", description: "Sucesión de hechos.", example: "La historia del pueblo era muy antigua." },
  { id: 157, name: "Narrador", description: "Quien cuenta una historia.", example: "El narrador relataba los sucesos con detalle." },
  { id: 158, name: "Personaje", description: "Ser que participa en un relato.", example: "El personaje principal enfrentó grandes desafíos." },
  { id: 159, name: "Protagonista", description: "Personaje principal.", example: "El protagonista salvó al reino del peligro." },
  { id: 160, name: "Antagonista", description: "Personaje que se opone al protagonista.", example: "El antagonista tramaba un plan secreto." },
  { id: 161, name: "Escena", description: "Parte de una historia.", example: "La escena final fue muy emocionante." },
  { id: 162, name: "Diálogo", description: "Conversación entre personajes.", example: "El diálogo reveló la verdad del misterio." },
  { id: 163, name: "Acción", description: "Lo que ocurre en la historia.", example: "La acción se intensificó con la llegada del villano." },
  { id: 164, name: "Conflicto", description: "Problema central del relato.", example: "El conflicto entre los reinos desencadenó la guerra." },
  { id: 165, name: "Final", description: "Conclusión del cuento.", example: "El final dejó a todos sorprendidos." },
  { id: 166, name: "Moraleja", description: "Enseñanza del relato.", example: "La moraleja del cuento es siempre decir la verdad." },
  { id: 167, name: "Tradición", description: "Costumbre transmitida por generaciones.", example: "La tradición de encender velas continúa cada año." },
  { id: 168, name: "Costumbre", description: "Hábito de una comunidad.", example: "Es costumbre saludar al llegar a la casa." },
  { id: 169, name: "Cultura", description: "Conjunto de conocimientos y valores.", example: "La cultura del pueblo se refleja en sus festivales." },
  { id: 170, name: "Pueblo", description: "Grupo de personas que habitan un lugar.", example: "El pueblo se unió para reconstruir la plaza." },
  { id: 171, name: "Campesino", description: "Persona que trabaja en el campo.", example: "El campesino cultivaba maíz y papas." },
  { id: 172, name: "Hacienda", description: "Finca grande con cultivos o ganado.", example: "La hacienda tenía extensos campos de trigo." },
  { id: 173, name: "Ciudad", description: "Lugar grande con muchos habitantes.", example: "La ciudad estaba llena de luces y sonidos." },
  { id: 174, name: "Barrio", description: "Parte de una ciudad.", example: "Vivían en un barrio tranquilo y seguro." },
  { id: 175, name: "Iglesia", description: "Templo cristiano.", example: "La iglesia estaba decorada con vitrales." },
  { id: 176, name: "Catedral", description: "Iglesia principal de una ciudad.", example: "La catedral se alzaba imponente en el centro." },
  { id: 177, name: "Atrio", description: "Entrada amplia de una iglesia.", example: "El atrio estaba lleno de feligreses." },
  { id: 178, name: "Campana", description: "Instrumento que suena en las torres.", example: "La campana anunció el inicio de la misa." },
  { id: 179, name: "Sacerdote", description: "Persona que dirige los actos religiosos.", example: "El sacerdote bendijo a los fieles." },
  { id: 180, name: "Fraile", description: "Religioso que vive en comunidad.", example: "El fraile enseñaba a los niños del convento." },
  { id: 181, name: "Cristo", description: "Figura de Jesús en la cruz.", example: "La estatua de Cristo dominaba la plaza." },
  { id: 182, name: "Pecado", description: "Falta contra lo moral o religioso.", example: "El pecado se perdonaba con arrepentimiento." },
  { id: 183, name: "Oración", description: "Comunicación con Dios.", example: "Hizo una oración antes de dormir." },
  { id: 184, name: "Milagro", description: "Hecho sobrenatural.", example: "El niño sobrevivió milagrosamente al accidente." },
  { id: 185, name: "Altar", description: "Mesa donde se celebra misa.", example: "El sacerdote colocó las velas en el altar." },
  { id: 186, name: "Cruz", description: "Símbolo cristiano.", example: "La cruz estaba decorada con flores." },
  { id: 187, name: "Fe", description: "Creencia en algo sin verlo.", example: "Tenía fe en que todo saldría bien." },
  { id: 188, name: "Arrepentimiento", description: "Sentir culpa por un error.", example: "Mostró arrepentimiento por sus malas acciones." },
  { id: 189, name: "Perdón", description: "Acto de disculpar.", example: "Pidió perdón por su equivocación." },
  { id: 190, name: "Bendición", description: "Favor o protección divina.", example: "Recibió la bendición del sacerdote." },
  { id: 191, name: "Culpa", description: "Responsabilidad por algo malo.", example: "Sintió culpa por romper la ventana." },
  { id: 192, name: "Castigo", description: "Consecuencia de una falta.", example: "El castigo fue enseñar a reparar lo roto." },
  { id: 193, name: "Recompensa", description: "Premio por un buen acto.", example: "Recibió una recompensa por su valentía." },
  { id: 194, name: "Miedo", description: "Sensación ante un peligro.", example: "El miedo lo paralizó ante el animal salvaje." },
  { id: 195, name: "Valor", description: "Fuerza para enfrentar el miedo.", example: "Con valor, cruzó el puente colgante." },
  { id: 196, name: "Sueño", description: "Deseo o imágenes al dormir.", example: "Tuvo un sueño maravilloso lleno de aventuras." },
  { id: 197, name: "Pesadilla", description: "Sueño que causa miedo.", example: "Se despertó asustado de una pesadilla." },
  { id: 198, name: "Esperanza", description: "Confianza en que algo saldrá bien.", example: "Nunca perdió la esperanza de encontrar a su amigo." },
  { id: 199, name: "Destino", description: "Lo que está escrito que suceda.", example: "Creía que su destino era ser explorador." },
  { id: 200, name: "Recuerdo", description: "Memoria de algo pasado.", example: "Guardaba un recuerdo de su infancia en un cajón." }
];